// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wordle.TrackerSupreme.Infrastructure.Database;

#nullable disable

namespace Wordle.TrackerSupreme.Migrations.Migrations
{
    [DbContext(typeof(WordleTrackerSupremeDbContext))]
    [Migration("20260710193816_AddImportedNytArchiveFlag")]
    partial class AddImportedNytArchiveFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.DailyPuzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("NytPuzzleId")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicPuzzleNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date");

                    b.Property<string>("Solution")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Stream")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NytPuzzleId")
                        .IsUnique()
                        .HasFilter("\"NytPuzzleId\" IS NOT NULL");

                    b.HasIndex("PuzzleDate", "Stream")
                        .IsUnique()
                        .HasFilter("\"IsPractice\" = false");

                    b.ToTable("DailyPuzzles");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.GuessAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GuessNumber")
                        .HasColumnType("integer");

                    b.Property<string>("GuessWord")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("PlayerPuzzleAttemptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerPuzzleAttemptId", "GuessNumber")
                        .IsUnique();

                    b.ToTable("Guesses");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.LetterEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuessAttemptId")
                        .HasColumnType("uuid");

                    b.Property<char>("Letter")
                        .HasColumnType("character(1)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuessAttemptId", "Position")
                        .IsUnique();

                    b.ToTable("LetterEvaluations");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.NytImportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AggregateGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Conflicts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Imported")
                        .HasColumnType("integer");

                    b.Property<int>("MissingFromNyt")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<int>("Requested")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("PlayerId", "CreatedOn");

                    b.ToTable("NytImportSessions");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.PlayerPuzzleAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("DailyPuzzleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsImportedArchive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("NytImportSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PlayedInHardMode")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DailyPuzzleId");

                    b.HasIndex("NytImportSessionId");

                    b.HasIndex("PlayerId", "DailyPuzzleId")
                        .IsUnique();

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.GuessAttempt", b =>
                {
                    b.HasOne("Wordle.TrackerSupreme.Domain.Models.PlayerPuzzleAttempt", "PlayerPuzzleAttempt")
                        .WithMany("Guesses")
                        .HasForeignKey("PlayerPuzzleAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerPuzzleAttempt");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.LetterEvaluation", b =>
                {
                    b.HasOne("Wordle.TrackerSupreme.Domain.Models.GuessAttempt", "GuessAttempt")
                        .WithMany("Feedback")
                        .HasForeignKey("GuessAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuessAttempt");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.NytImportSession", b =>
                {
                    b.HasOne("Wordle.TrackerSupreme.Domain.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.PlayerPuzzleAttempt", b =>
                {
                    b.HasOne("Wordle.TrackerSupreme.Domain.Models.DailyPuzzle", "DailyPuzzle")
                        .WithMany("Attempts")
                        .HasForeignKey("DailyPuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wordle.TrackerSupreme.Domain.Models.NytImportSession", "NytImportSession")
                        .WithMany("ImportedAttempts")
                        .HasForeignKey("NytImportSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wordle.TrackerSupreme.Domain.Models.Player", "Player")
                        .WithMany("Attempts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyPuzzle");

                    b.Navigation("NytImportSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.DailyPuzzle", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.GuessAttempt", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.NytImportSession", b =>
                {
                    b.Navigation("ImportedAttempts");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.Player", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Wordle.TrackerSupreme.Domain.Models.PlayerPuzzleAttempt", b =>
                {
                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
