import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');
const apiBase = process.env.WTS_API_BASE_URL ?? 'https://wordle.trackersupreme.dk';
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
for (const file of ['manifest.json', 'popup.html', 'popup.css', 'popup.js', 'extraction.js', 'import-flow.js']) await cp(path.join(root, file), path.join(dist, file));
await writeFile(path.join(dist, 'config.js'), `export const API_BASE_URL = ${JSON.stringify(apiBase.replace(/\/$/, ''))};\n`);
const manifest = JSON.parse(await readFile(path.join(dist, 'manifest.json'), 'utf8'));
manifest.host_permissions = [`${new URL(apiBase).origin}/*`];
await writeFile(path.join(dist, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
const zip = path.join(root, 'wordle-tracker-supreme-extension.zip');
await rm(zip, { force: true });
const result = spawnSync('zip', ['-qr', zip, '.'], { cwd: dist, stdio: 'inherit' });
if (result.status !== 0) throw new Error('The zip command failed.');
console.log(`Built ${zip} for ${apiBase}`);
